making release action work

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,8 +9,10 @@ on:
 
 env:
   VERSION_SCHEMA: semantic # 'semantic' or 'calendar'
+  ACCOUNT_NAME: RailEduKit #  provide account name: https://github.com/ACCOUNT_NAME/repossitory
   REPO_NAME: Learning-Matrix-Railway-Signalling # provide repository name: https://github.com/railedukit/REPO_NAME
   ZENODO_COLLECTION: 7689889 # provide Zenodo collection number $COLLECTION from DOI: 10.5281/zenodo.COLLECTION
+  MASTODON_INSTANCE: fediscience.org # i.e. https://MASTODON_INSTANCE/ without the protocol part
 
 jobs:
   version:
@@ -52,10 +54,10 @@ jobs:
           # check with regular expressions
           STATUS=0
           VER_REGEX="a^"
-          if [[ $VERSION_SCHEMA = "semantic" ]]; then
+          if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
             VER_REGEX="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$"
           fi
-          if [[ $VERSION_SCHEMA = "calendar" ]]; then
+          if [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
             VER_REGEX="^([0-9]{4}).(1[0-2]|0[1-9])$"
           fi
           if [[ ! $VERSION =~ $VER_REGEX ]]; then
@@ -63,16 +65,16 @@ jobs:
           fi
           if [ $STATUS = 1 ]; then
             echo "- :no_entry_sign: format does not follow a versioning schema" >> $GITHUB_STEP_SUMMARY
-            if [[ $VERSION_SCHEMA = "semantic" ]]; then
+            if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
               echo ":warning: Please see https://semver.org/ for further information." >> $GITHUB_STEP_SUMMARY
-            elif [[ $VERSION_SCHEMA = "calendar" ]]; then
+            elif [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
               echo ":warning: Please see https://calver.org/ for further information." >> $GITHUB_STEP_SUMMARY
             fi
             exit 1
           else
-            if [[ $VERSION_SCHEMA = "semantic" ]]; then
+            if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
               echo "- follows the semantic versioning schema format :white_check_mark:" >> $GITHUB_STEP_SUMMARY
-            elif [[ $VERSION_SCHEMA = "calendar" ]]; then
+            elif [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
               echo "- follows the calendar versioning schema format :white_check_mark:" >> $GITHUB_STEP_SUMMARY
             fi
           fi
@@ -88,7 +90,7 @@ jobs:
             VERSION_MINOR=$(echo $VERSION | cut -d. -f2 )
             CURRENT_VERSION_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1 )
             CURRENT_VERSION_MINOR=$(echo $CURRENT_VERSION | cut -d. -f2 )
-            if [[ $VERSION_SCHEMA = "semantic" ]]; then
+            if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
               VERSION_PATCH=$(echo $VERSION | cut -d. -f3 )
               CURRENT_VERSION_PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 )
               if [[ $VERSION_MAJOR -eq CURRENT_VERSION_MAJOR ]]; then
@@ -117,7 +119,7 @@ jobs:
                   STATUS=1
                 fi
               fi
-            elif [[ $VERSION_SCHEMA = "calendar" ]]; then
+            elif [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
               if [[ $VERSION_MAJOR -eq CURRENT_VERSION_MAJOR ]]; then
                 if [[ ! $VERSION_MINOR -gt CURRENT_VERSION_MINOR ]]; then
                   STATUS=1
@@ -127,10 +129,10 @@ jobs:
               fi
             fi
             if [ $STATUS = 1 ]; then
-              if [[ $VERSION_SCHEMA = "semantic" ]]; then
+              if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
                 echo "- :no_entry_sign: Version skipped steps from the previous version $CURRENT_VERSION and thus does not follow the semantic versioning schema." >> $GITHUB_STEP_SUMMARY
                 echo "- :warning: Please see https://semver.org/ for further information." >> $GITHUB_STEP_SUMMARY
-              elif [[ $VERSION_SCHEMA = "calendar" ]]; then
+              elif [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
                 echo "- :no_entry_sign: Version is not higher then the previous version $CURRENT_VERSION and thus does not follow the calendar versioning schema." >> $GITHUB_STEP_SUMMARY
                 echo "- :warning: Please see https://calver.org/ for further information." >> $GITHUB_STEP_SUMMARY
               fi
@@ -168,7 +170,7 @@ jobs:
           ## ---------------------------------
           TOP=$(grep -n "## \[Unreleased\]" CHANGELOG.md | cut -d: -f1)
           if [ "$CURRENT_VERSION" = "no_version" ]; then
-            BOTTOM=$(grep -n -m 1 "\[Unreleased\]: https://github.com/railedukit/" CHANGELOG.md | cut -d: -f1)
+            BOTTOM=$(grep -n -m 1 "\[Unreleased\]: https://github.com/${{ env.ACCOUNT_NAME }}/" CHANGELOG.md | cut -d: -f1)
           else
             BOTTOM=$(grep -n -m 1 "## Version \[$CURRENT_VERSION\]" CHANGELOG.md | cut -d: -f1)
           fi
@@ -211,7 +213,7 @@ jobs:
         with:
           files: $FILES
           recursive: false
-          dest: $REPO_NAME-v${{ needs.version.outputs.new }}.zip
+          dest: ${{ env.REPO_NAME }}-v${{ needs.version.outputs.new }}.zip
       - run: echo "- creating ZIP-Archive for the new release :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
       # 4. upload artifact to share it with other jobs
@@ -219,7 +221,7 @@ jobs:
         with:
           path: |
             release-note-v${{ needs.version.outputs.new }}.md
-            $REPO_NAME-v${{ needs.version.outputs.new }}.zip
+            ${{ env.REPO_NAME }}-v${{ needs.version.outputs.new }}.zip
           if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
       - run: echo "- providing ZIP-Archive and release notes for other jobs :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
@@ -238,8 +240,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ github.ref }}
+          tag_name: v${{ needs.version.outputs.new }}
+          release_name: Release v${{ needs.version.outputs.new }}
           body_path: artifact/release-note-v${{ needs.version.outputs.new }}.md
           draft: false
           prerelease: false
@@ -251,8 +253,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: artifact/$REPO_NAME-v${{ needs.version.outputs.new }}.zip
-          asset_name: $REPO_NAME-v${{ needs.version.outputs.new }}.zip
+          asset_path: artifact/${{ env.REPO_NAME }}-v${{ needs.version.outputs.new }}.zip
+          asset_name: ${{ env.REPO_NAME }}-v${{ needs.version.outputs.new }}.zip
           asset_content_type: application/zip
 
       # 4. publish release on github
@@ -263,133 +265,133 @@ jobs:
         with:
           id: ${{ steps.create_release.outputs.id }}
 
-  zenodo:
-    needs: [create_package, version]
-    name: "publish on zenodo"
-    outputs:
-      doi: ${{ steps.zenodraft.outputs.doi }}
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "Archiving package on zenodo to get a DOI:" >> $GITHUB_STEP_SUMMARY
-      # 1. download artifact in folder artifact/ and move it one level up and checkout the repo
-      - uses: actions/checkout@v3
-      - uses: actions/download-artifact@v3
-      - run: |
-          mv ./artifact/$REPO_NAME-v${{ needs.version.outputs.new }}.zip ./
-          echo "- getting ZIP-Archive and release notes :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  # zenodo:
+  #   needs: [create_package, version]
+  #   name: "publish on zenodo"
+  #   outputs:
+  #     doi: ${{ steps.zenodraft.outputs.doi }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: echo "Archiving package on zenodo to get a DOI:" >> $GITHUB_STEP_SUMMARY
+  #     # 1. download artifact in folder artifact/ and move it one level up and checkout the repo
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/download-artifact@v3
+  #     - run: |
+  #         mv ../artifact/${{ env.REPO_NAME }}-v${{ needs.version.outputs.new }}.zip ../
+  #         echo "- getting ZIP-Archive and release notes :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-      # 2. install zenodraft
-      - name: "install zenodraft"
-        env:
-          URL: "https://zenodo.org/"
-        run: |
-          STATUS=0
-          npm install -g zenodraft
-          echo "- installing zenodraft :white_check_mark:" >> $GITHUB_STEP_SUMMARY
-          if ! curl --output /dev/null --silent --head --fail "$URL"; then
-            STATUS=1
-          fi
-          if [ $STATUS = 1 ]; then
-            echo "- :no_entry_sign: $URL is not reachable" >> $GITHUB_STEP_SUMMARY
-            echo ":warning: Please re-run action later!" >> $GITHUB_STEP_SUMMARY
-            echo ":warning: Please remove github release manually!" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          else
-            echo "- $URL is reachable :white_check_mark:" >> $GITHUB_STEP_SUMMARY
-          fi
+  #     # 2. install zenodraft
+  #     - name: "install zenodraft"
+  #       env:
+  #         URL: "https://zenodo.org/"
+  #       run: |
+  #         STATUS=0
+  #         npm install -g zenodraft
+  #         echo "- installing zenodraft :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #         if ! curl --output /dev/null --silent --head --fail "$URL"; then
+  #           STATUS=1
+  #         fi
+  #         if [ $STATUS = 1 ]; then
+  #           echo "- :no_entry_sign: $URL is not reachable" >> $GITHUB_STEP_SUMMARY
+  #           echo ":warning: Please re-run action later!" >> $GITHUB_STEP_SUMMARY
+  #           echo ":warning: Please remove github release manually!" >> $GITHUB_STEP_SUMMARY
+  #           exit 1
+  #         else
+  #           echo "- $URL is reachable :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #         fi
 
-      # 3. Update zenodo metadata.json
-      - name: "Update zenodo metadata.json"
-        run: |
-          VERSION=${{ needs.version.outputs.new }}
-          sed -i".backup" -e"s/\"version\": \"%%\[SCRIPT\]\"/\"version\": \"$VERSION\"/g" .github/zenodo/metadata.json
-          echo "- updating zenodo metadata :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #     # 3. Update zenodo metadata.json
+  #     - name: "Update zenodo metadata.json"
+  #       run: |
+  #         VERSION=${{ needs.version.outputs.new }}
+  #         sed -i".backup" -e"s/\"version\": \"%%\[SCRIPT\]\"/\"version\": \"$VERSION\"/g" .github/zenodo/metadata.json
+  #         echo "- updating zenodo metadata :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-      # 4. upload new release to zenodo
-      - name: "uploading to zenodo"
-        id: zenodraft
-        env:
-          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
-        run: |
-          DOI=$(zenodraft deposition create version $ZENODO_COLLECTION)
-          zenodraft file add $DOI $REPO_NAME-v*.zip
-          zenodraft metadata update $DOI .github/zenodo/metadata.json
-          zenodraft deposition publish $DOI
-          ## =================================
-          ## provide variables for subsequent jobs
-          ## ---------------------------------
-          echo "doi=10.5281/zenodo.$DOI" >> $GITHUB_OUTPUT
-          echo "- publish release at zenodo with DOI: 10.5281/zenodo.$DOI :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #     # 4. upload new release to zenodo
+  #     - name: "uploading to zenodo"
+  #       id: zenodraft
+  #       env:
+  #         ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
+  #       run: |
+  #         DOI=$(zenodraft deposition create version ${{ env.ZENODO_COLLECTION }})
+  #         zenodraft file add $DOI ${{ env.REPO_NAME }}-v*.zip
+  #         zenodraft metadata update $DOI .github/zenodo/metadata.json
+  #         zenodraft deposition publish $DOI
+  #         ## =================================
+  #         ## provide variables for subsequent jobs
+  #         ## ---------------------------------
+  #         echo "doi=10.5281/zenodo.$DOI" >> $GITHUB_OUTPUT
+  #         echo "- publish release at zenodo with DOI: 10.5281/zenodo.$DOI :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-  update_repository:
-    needs: [zenodo, version]
-    name: "updating CITATION.cff and CHANGELOG.md"
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "Updating CITATION.cff and CHANGELOG.md:" >> $GITHUB_STEP_SUMMARY
-      # 1. checkout the repo
-      - name: "checkout"
-        uses: actions/checkout@v3
-        # with:
-        #   ref: main
+  # update_repository:
+  #   needs: [zenodo, version]
+  #   name: "updating CITATION.cff and CHANGELOG.md"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: echo "Updating CITATION.cff and CHANGELOG.md:" >> $GITHUB_STEP_SUMMARY
+  #     # 1. checkout the repo
+  #     - name: "checkout"
+  #       uses: actions/checkout@v3
+  #       # with:
+  #       #   ref: main
 
-      # 2. update CITATION.cff
-      - name: "update CITATION.cff"
-        run: |
-          DATE=$(date "+%Y-%m-%d")
-          VERSION=${{ needs.version.outputs.new }}
-          DOI=${{ needs.publish_zenodo.outputs.doi }}
-          echo "find lines in CITATION.cff"
-          VERSION_LINE=$(grep -n '^version:' CITATION.cff | cut -d: -f1)
-          DATE_LINE=$(grep -n '^date-released:' CITATION.cff | cut -d: -f1)
-          echo "select the second DOI"
-          DOI_LINE=$(grep -n 'type: doi' CITATION.cff | cut -d: -f1 | awk "NR==2")
-          DOI_LINE=$(( $DOI_LINE + 1 ))
-          echo "update CITATION.cff"
-          sed -i -- "${VERSION_LINE}s|.*|version: $VERSION|" CITATION.cff
-          sed -i -- "${DATE_LINE}s|.*|date-released: ${DATE}|" CITATION.cff
-          sed -i -- "${DOI_LINE}s|.*|    value: $DOI|" CITATION.cff
-          echo "- updated CITATION.cff :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #     # 2. update CITATION.cff
+  #     - name: "update CITATION.cff"
+  #       run: |
+  #         DATE=$(date "+%Y-%m-%d")
+  #         VERSION=${{ needs.version.outputs.new }}
+  #         DOI=${{ needs.publish_zenodo.outputs.doi }}
+  #         echo "find lines in CITATION.cff"
+  #         VERSION_LINE=$(grep -n '^version:' CITATION.cff | cut -d: -f1)
+  #         DATE_LINE=$(grep -n '^date-released:' CITATION.cff | cut -d: -f1)
+  #         echo "select the second DOI"
+  #         DOI_LINE=$(grep -n 'type: doi' CITATION.cff | cut -d: -f1 | awk "NR==2")
+  #         DOI_LINE=$(( $DOI_LINE + 1 ))
+  #         echo "update CITATION.cff"
+  #         sed -i -- "${VERSION_LINE}s|.*|version: $VERSION|" CITATION.cff
+  #         sed -i -- "${DATE_LINE}s|.*|date-released: ${DATE}|" CITATION.cff
+  #         sed -i -- "${DOI_LINE}s|.*|    value: $DOI|" CITATION.cff
+  #         echo "- updated CITATION.cff :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-      # 3. update CHANGELOG.md
-      - name: "update CHANGELOG.md"
-        run: |
-          DATE=$(date "+%Y-%m-%d")
-          VERSION=${{ needs.version.outputs.new }}
-          URL="https://github.com/railedukit/$REPO_NAME"
-          CURRENT_VERSION=${{ needs.version.outputs.current }}
-          if [[ $VERSION_SCHEMA = "semantic" ]]; then
-            sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION] $DATE" CHANGELOG.md
-          elif [[ $VERSION_SCHEMA = "calendar" ]]; then
-            sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION]" CHANGELOG.md
-          fi
-          if [ "$CURRENT_VERSION" = "no_version" ]; then
-            sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/releases/tag/v$VERSION|" CHANGELOG.md
-          else
-            sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/compare/v$CURRENT_VERSION...v$VERSION|" CHANGELOG.md
-          fi
-          echo "- updated CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #     # 3. update CHANGELOG.md
+  #     - name: "update CHANGELOG.md"
+  #       run: |
+  #         DATE=$(date "+%Y-%m-%d")
+  #         VERSION=${{ needs.version.outputs.new }}
+  #         URL="https://github.com/${{ env.ACCOUNT_NAME }}/${{ env.REPO_NAME }}"
+  #         CURRENT_VERSION=${{ needs.version.outputs.current }}
+  #         if [[ ${{ env.VERSION_SCHEMA }} = "semantic" ]]; then
+  #           sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION] $DATE" CHANGELOG.md
+  #         elif [[ ${{ env.VERSION_SCHEMA }} = "calendar" ]]; then
+  #           sed -i -- "/## \[Unreleased\]/a\\\n\n## Version [$VERSION]" CHANGELOG.md
+  #         fi
+  #         if [ "$CURRENT_VERSION" = "no_version" ]; then
+  #           sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/releases/tag/v$VERSION|" CHANGELOG.md
+  #         else
+  #           sed -i -- "s|^\[Unreleased\]: .*$|\[Unreleased\]: $URL/compare/v$VERSION...main\n\[$VERSION\]: $URL/compare/v$CURRENT_VERSION...v$VERSION|" CHANGELOG.md
+  #         fi
+  #         echo "- updated CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-      # 4. push the change back to main
-      - name: push
-        uses: EndBug/add-and-commit@v9
-        with:
-          message: "updated to ${{ needs.version.outputs.new }} (via github action)"
-          add: CITATION.cff CHANGELOG.md
-          author_name: railedukit
-          author_email: railedukit@ownx.net
-          tag: 'v${{ needs.version.outputs.new }} --force'
-      - run: echo "- updated repository with new CITATION.cff and CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+  #     # 4. push the change back to main
+  #     - name: push
+  #       uses: EndBug/add-and-commit@v9
+  #       with:
+  #         message: "updated to ${{ needs.version.outputs.new }} (via github action)"
+  #         add: CITATION.cff CHANGELOG.md
+  #         author_name: ${{ env.ACCOUNT_NAME }}
+  #         author_email: railedukit@ownx.net
+  #         tag: 'v${{ needs.version.outputs.new }} --force'
+  #     - run: echo "- updated repository with new CITATION.cff and CHANGELOG.md :white_check_mark:" >> $GITHUB_STEP_SUMMARY
 
-  publish_mastodon:
-    needs: [zenodo, version]
-    name: "Toot about it on fediscience.org"
-    runs-on: ubuntu-latest
-    steps:
-      - uses: cbrgm/mastodon-github-action@v1
-        with:
-          message: "The new version ${{ needs.version.outputs.new }} of $REPO_NAME is available! DOI: https://doi.org/${{ needs.zenodo.outputs.doi }}."
-          visibility: "public" # default: public
-        env:
-          MASTODON_URL: "https://fediscience.org/"
-          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
+  # publish_mastodon:
+  #   needs: [zenodo, version]
+  #   name: "Toot about it on ${{ env.MASTODON_INSTANCE }}"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: cbrgm/mastodon-github-action@v1
+  #       with:
+  #         message: "The new version ${{ needs.version.outputs.new }} of ${{ env.REPO_NAME }} is available! DOI: https://doi.org/${{ needs.zenodo.outputs.doi }}."
+  #         visibility: "public" # default: public
+  #       env:
+  #         MASTODON_URL: "https://${{ env.MASTODON_INSTANCE }}/"
+  #         MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
